Repository AlesInfiny/dotnet-libraries, pull requests merged in 2025-03, with the labels that each got.

#10 Maris.Logging.Testingのreadmeの軽微な修正
  .textlintrc
  src/Maris.Logging.Testing/README.md
Labels: target: Maris.Logging.Testing

#14 ワークフローにpermissionsの設定を追加する
  .github/workflows/lint-documents.yml
  .github/workflows/maris-logging-testing.ci.yml
Labels: CI/CD

#16 test-reporterの導入とカバレッジレポートの保存
  .github/workflows/maris-logging-testing.ci.yml
Labels: 内部の改善, CI/CD

#18 新しいIssueおよびPull Requestをプロジェクトに自動で追加できるようにする
  .github/workflows/auto-add-issue-and-pr-to-project.yml
Labels: 内部の改善

#19 Maris.Logging.TestingのREADMEを英訳する
  images/test-explorer-log.en.png
  images/test-explorer-log.ja.png
  src/Maris.Logging.Testing/Maris.Logging.Testing.csproj
  src/Maris.Logging.Testing/README.ja.md
  src/Maris.Logging.Testing/README.md
Labels: target: Maris.Logging.Testing

#20 依存ライブラリのバージョンを8系の古いものに変更する
  Directory.Packages.props
Labels: target: Maris.Logging.Testing, nuget

#22 リリースノートからMaris.Logging.Testingのnuget.orgページへのリンクを追加
  .github/release.yml
Labels: 内部の改善
